<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>UnitConversion.Tests</AssemblyName>
    <RootNamespace>UnitConversion.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Domain\UnitConversion.Domain.csproj" />
    <ProjectReference Include="..\Core\Application\UnitConversion.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\UnitConversion.Infrastructure.csproj" />
    <ProjectReference Include="..\API\UnitConversion.Api.csproj" />
  </ItemGroup>

</Project>
