<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>UnitConversion.Application</AssemblyName>
    <RootNamespace>UnitConversion.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\UnitConversion.Domain.csproj" />
    <ProjectReference Include="..\Common\UnitConversion.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

</Project>
